"""Non-circular physical invariant checks for the Gaussian plume model.

Run:
    python -m algorithm.diffusion.test_physical_invariants

These checks do not compare the model against data generated by the same
implementation. They verify conservation and physical constraints that should
hold for a passive tracer plume.
"""

from __future__ import annotations

import math
import sys

import numpy as np

from .gaussian_plume import (
    briggs_sigma_y,
    briggs_sigma_z,
    integrated_crosswind_mass_flux,
    steady_plume_mass_conc,
    wind_at_height,
)


def _assert(condition: bool, message: str, failures: list[str]) -> None:
    if not condition:
        failures.append(message)


def check_mass_conservation(failures: list[str]) -> None:
    cases = [
        {"q": 20.0, "wind": 2.0, "height": 0.5, "stability": "B", "urban": False},
        {"q": 80.0, "wind": 4.5, "height": 8.0, "stability": "D", "urban": True},
        {"q": 120.0, "wind": 6.0, "height": 25.0, "stability": "F", "urban": False},
    ]
    for case in cases:
        wind = wind_at_height(case["wind"], case["height"], case["stability"])
        for distance in (100.0, 400.0, 1000.0):
            flux = integrated_crosswind_mass_flux(
                case["q"],
                wind,
                distance,
                case["height"],
                case["stability"],
                case["urban"],
                y_samples=501,
                z_samples=501,
            )
            rel_error = abs(flux - case["q"]) / case["q"]
            _assert(
                rel_error < 0.025,
                f"mass flux error {rel_error:.4f} exceeds tolerance at {distance} m",
                failures,
            )


def check_ground_reflection(failures: list[str]) -> None:
    q = 50.0
    wind = 3.0
    distance = 250.0
    stability = "D"
    urban = False
    plume = float(steady_plume_mass_conc(q, wind, distance, 0.0, 0.0, 0.0, stability, urban))
    sigma_y = float(briggs_sigma_y(distance, stability, urban))
    sigma_z = float(briggs_sigma_z(distance, stability, urban))
    single_source = q / (2.0 * math.pi * wind * sigma_y * sigma_z)
    _assert(
        abs(plume - 2.0 * single_source) / (2.0 * single_source) < 1e-9,
        "ground-level source should double the single-source term through reflection",
        failures,
    )


def check_nonnegative_finite_and_decay(failures: list[str]) -> None:
    distances = np.array([50.0, 100.0, 200.0, 400.0, 800.0, 1600.0])
    values = np.asarray(
        steady_plume_mass_conc(70.0, 4.0, distances, 0.0, 1.5, 0.5, "D", False),
        dtype=float,
    )
    _assert(bool(np.all(np.isfinite(values))), "centerline concentration must be finite", failures)
    _assert(bool(np.all(values >= 0.0)), "centerline concentration must be nonnegative", failures)
    _assert(
        bool(np.all(np.diff(values) < 0.0)),
        "centerline concentration should decay with distance for this stable scenario",
        failures,
    )


def check_stability_width_order(failures: list[str]) -> None:
    distance = 500.0
    sigma_y = [float(briggs_sigma_y(distance, stability, False)) for stability in "ABCDEF"]
    sigma_z = [float(briggs_sigma_z(distance, stability, False)) for stability in "ABCDEF"]
    _assert(
        bool(np.all(np.diff(sigma_y) < 0.0)),
        "sigma_y should narrow from unstable A to stable F over open terrain",
        failures,
    )
    _assert(
        bool(np.all(np.diff(sigma_z) < 0.0)),
        "sigma_z should narrow from unstable A to stable F over open terrain",
        failures,
    )


def main() -> int:
    failures: list[str] = []
    check_mass_conservation(failures)
    check_ground_reflection(failures)
    check_nonnegative_finite_and_decay(failures)
    check_stability_width_order(failures)

    print("Gaussian plume physical invariant checks")
    if failures:
        print("Result: failed")
        for failure in failures:
            print(f" - {failure}")
        return 1
    print("Result: passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
