module.exports = {
    extends: ['@commitlint/config-conventional'],
    // 校验规则
    rules: {
        'type-enum': [
            2,
            'always',
            [
                'feat',
                'fix',
                'docs',
                'style',
                'refactor',
                'perf',
                'test',
                'chore',
                'revert',
                'build',
            ],
        ],
        'type-case': [0],
        'type-empty': [0],
        'scope-empty': [2, 'never'],
        'scope-enum': [
            2,
            'always',
            [
                'algorithm',
                'api',
                'architecture',
                'audit',
                'auth',
                'backend',
                'build',
                'ci',
                'db',
                'deploy',
                'docs',
                'equipment',
                'frontend',
                'home',
                'inversion',
                'monitoring',
                'policy',
                'readme',
                'requirements',
                'security',
                'smart-map',
                'startup',
                'test',
                'tooling',
                'yolo',
            ],
        ],
        'scope-case': [0],
        'subject-full-stop': [0, 'never'],
        'subject-case': [0, 'never'],
        'header-max-length': [2, 'always', 72],
    },
}
